### ISSUE TITLE
the wheel is at the entrance?

### ISSUE THREAD

**Issue by ghost** [Sn0wBiT/esx_tpnrp_luckywheel#9]
the wheel is at the entrance?

photo:https://drive.google.com/open?id=1uBLNRNh97Lmlim9EcARtKmx6NjXflx36

**Comment by Demo4889** [comment]
No, that is only a display... not the actual wheel to spin

**Comment by ghost** [comment]
> No, that is only a display... not the actual wheel to spin

But there's no wheel in the actual casino?

**Comment by MadLad1Clip** [comment]
Seeing the same prob

**Comment by Demo4889** [comment]
It all depends on what map you are using for the casino. Some have the base already, and some do not. You will need to change the coordinates for the location of the wheel and the wheelbase itself (if required)

**Comment by MadLad1Clip** [comment]
yeah i have managed to get the wheel in place its a little janky on the spinning hoping ill be able to clean it up.

**Comment by Demo4889** [comment]
Yes, I saw that issue as well when you go to spin it. Not sure what causes that and I know people have gotten it fixed before, but they won't share their fixes

**Comment by MadLad1Clip** [comment]
Shock that people are not sharing, hoping i can get it fixed. If i remember i will share it here.
